
package:
  name: mapshader
  version: 0.0.6

source:
  path: ..

requirements:
  host:
    - python
    - setuptools
    - pyct
  run:
    - python
    - xarray-spatial
    - datashader
    - click
    - tbb
    - geopandas
    - rasterio
    - rioxarray
    - flask
    - descartes
    - matplotlib
    - spatialpandas
    - pyct

test:
  requires:
    - pytest >=2.8.5
  imports:
    - mapshader

about:
  home: https://github.com/makepath/mapshader
  license: MIT
