{% set sdata = load_setup_py_data() %}

package:
  name: mapshader
  version: 0.0.6

source:
  path: ..

requirements:
  host:
    - python
    - setuptools
    - pyct
  run:
    - python
    {% for dep in sdata.get('install_requires',{}) %}
    - {{ dep }}
    {% endfor %}

test:
  requires:
    - pytest
  imports:
    - mapshader

about:
  home: https://github.com/makepath/mapshader
  license: MIT
