
package:
  name: mapshader
  version: 0.0.6

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - xarray-spatial
    - datashader
    - click
    - tbb
    - geopandas
    - rasterio
    - rioxarray
    - flask
    - descartes
    - matplotlib
    - spatialpandas
    - psutil

test:
  requires:
    - pytest >=2.8.5
  imports:
    - mapshader

about:
  home: https://github.com/makepath/mapshader
  license: MIT
