name: Python Test Suite

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Get some info
      run: |
        $CONDA/bin/conda info

    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory

    - name: Activate environment
      run: |
        $CONDA/bin/pip install pytest
        $CONDA/bin/pip install flake8

    - name: Install Mapshader code
      run: |
        $CONDA/bin/pip install -e .

    - name: Test with pytest
      run: |
        $CONDA/bin/pip install pytest
        $CONDA/bin/pytest -vvs mapshader/tests
